work_dir: ./work_dir/recognition/kinetics_skeleton/gcn_cnn
model_saved_name: ./runs/GCN_CNN
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 150
  data_path: ./kinetics/train_datafalse.npy
  label_path: ./kinetics/train_labelflase.pkl
  debug: True

test_feeder_args:
  data_path: ./kinetics/val_data.npy
  label_path: ./kinetics/val_label.pkl

# model
model: model.GcnCnn.Model
model_args:
  in_channels: 3
  num_class: 400
  edge_importance_weighting: True
  graph_args:
    layout: 'openpose'
    strategy: 'spatial'

# training
device: 0 #[0,1,2,3]
batch_size: 32  #256
test_batch_size: 32

#optim
base_lr: 0.1
step: [15, 20]
num_epoch: 20
nesterov: True
#num_worker: 2


